# Generated by Django 3.0.8 on 2020-09-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pet_pic',
            field=models.FilePathField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.FilePathField(blank=True),
        ),
    ]
