# Generated by Django 3.0.8 on 2020-09-21 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200907_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pet_pic',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.URLField(),
        ),
    ]
