# Generated by Django 3.0.8 on 2020-08-22 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0004_auto_20200822_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pledge',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='project',
            name='goal',
        ),
        migrations.AddField(
            model_name='project',
            name='post_code',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='seeking',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='suburb',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('img', models.URLField()),
                ('location', models.CharField(max_length=200)),
                ('supporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporter_donation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
