# Generated by Django 3.0.8 on 2020-08-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200822_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Donation_Items',
            },
        ),
    ]
