# Generated by Django 3.0.8 on 2020-08-26 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_donationitems'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='donationitems',
            table=None,
        ),
    ]
